version: '2'

services:
  vanilla:
    #image: 1drop/vanilla
    build:
      context: .
    restart: always
    environment:
      VIRTUAL_HOST: vanilla.docker
      VIRTUAL_PORT: 80
      MYSQL_HOST: 'vanilladb'
      MYSQL_USER: 'vanilla'
      MYSQL_PASSWORD: 'vanilla'
      MYSQL_DATABASE: 'vanilla'
    depends_on:
      - vanilladb
    volumes:
      - conf:/app/conf
      - uploads:/app/uploads
  vanilladb:
    image: mariadb:10
    # restart: always
    environment:
      MYSQL_USER: 'vanilla'
      MYSQL_PASSWORD: 'vanilla'
      MYSQL_DATABASE: 'vanilla'
      MYSQL_ROOT_PASSWORD: 'vanilla'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db:/var/lib/mysql

volumes:
  uploads:
    driver: local
  conf:
    driver: local
  db:
    driver: local